package muiz.demo.abac.core;

import org.neo4j.driver.Driver;
import org.neo4j.driver.Record;
import org.neo4j.driver.Session;
import org.neo4j.driver.exceptions.Neo4jException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * Executes cypher queries generated by the query generator and responds with whether access is allowed or not based on current request.
 */
@Component
public class PolicyEvaluator {
    private static final Logger LOGGER = LoggerFactory.getLogger(PolicyEvaluator.class.getName());

    private final Map<String, String> pathVariables;

    private final Driver driver;

    public PolicyEvaluator(Map<String, String> pathVariables, Driver driver) {
        this.pathVariables = pathVariables;
        this.driver = driver;
    }

    public boolean evaluate() {
        var policiesQueries = new PolicyQueryGenerator(pathVariables).getQueries();
        try (Session session = driver.session()) {
            for (var policyQuery : policiesQueries.entrySet()) {
                Record record = session.readTransaction(tx -> tx.run(policyQuery.getValue()).single());
                var results = record.asMap().entrySet().stream().findFirst();
                LOGGER.info(policyQuery.getValue());
                results.ifPresent(stringObjectEntry -> LOGGER.info(String.valueOf((Boolean) stringObjectEntry.getValue())));
            }
        } catch (Neo4jException ex) {
            LOGGER.error(ex.getMessage());
            throw ex;
        }
        return false;
    }
}
